## 1.고성능 수치 계산 Numpy


In [ ]:
# %pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/92/0f/7ceaaeaacb40567071e94dbf2c9480c0ae453d5bb4f52bea3892c39dc83c/numpy-2.4.2-cp312-cp312-win_amd64.whl.metadata
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.2/12.3 MB 2.3 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/12.3 MB 4.9 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/12.3 MB 6.9 MB/s eta 0:00:02
   ----- ---------------------------------- 1.7/12.3 MB 8.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/12.3 MB 9.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.3 MB 8.4 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.3 MB 8.5 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.3 MB 8.6 MB/s eta 0:00:02
   ------------ ------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
import numpy as np


In [37]:
np.__version__

'2.4.2'

In [38]:
def printinfo(array):
    print(f"shape:{array.shape}, dimension:{array.ndim}, dtype:{array.dtype}")

Numpy 배열Array생성하기

<img src="./img/2-차원.PNG">

## 1) array 함수를 사용하여 배열 생성하기

  ###1차원 배열 생성하기

In [39]:
array=np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [40]:
array.shape

(5,)

In [ ]:
array.ndim

1

In [ ]:
array.dtype

dtype('int64')

In [ ]:
printinfo(array)

shape:(5,), dimension:1, dtype:int64


2차원 배열생성하기

In [ ]:
list=[[1,2,3],[4,5,6]]
array2=np.array(list)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
printinfo(array2)

shape:(2, 3), dimension:2, dtype:int64


In [ ]:
array3=np.array(list,dtype=float)
array3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
printinfo(array3)

shape:(2, 3), dimension:2, dtype:float64


- 3차원생성하기

In [ ]:
array4=np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[2,3,4]]
                 ],dtype=float)
array4

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [2., 3., 4.]]])

In [ ]:
printinfo(array4)

shape:(2, 2, 3), dimension:3, dtype:float64


- 2)zeros, ones, empty함수를 사용하여 배열 생성하기

In [ ]:
np.zeros((3,3))
#모든값을 0인 배열을 만둘 수 있다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))
#모든 값을 1인 배열을 만들 수 있다. 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((4,4),dtype=int)
#empty():값이 초기화 되지 않는 배열을 만들 수 있다.

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

| 이름 | 점수 | 합격 |
|------|------|------|
| 철수 | 90 | O |
| 영희 | 75 | O |
| 민수 | 50 | X |

- [ ] 할 일
- [x] 완료

### 3) arrange함수를 사용하여 배열 생성하기

In [ ]:
array5=np.arange(10) # 시작, 끝, 간격
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array6=np.arange(0,11,2)
array6

array([ 0,  2,  4,  6,  8, 10])

### 3.ndaray속성
    arr.shape배열모양
    arr.ndim차원수
    arr.dtype데이터타입

In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


## 4.ndarray타입 변환: astype()함수이용

* 정수형 데이터 배열을 실수형 데이터 배열로 변환하기

In [35]:
arr_int=np.array([1,2,3,4,5])
arr_int.dtype

dtype('int64')

In [18]:
#생성할때 type을 지정할 수 있다.
arr_int=np.array([1,2,3,4,5],dtype='int')
arr_int.dtype

dtype('int64')

In [22]:
arr_float=arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

In [24]:
#문자형 데이터 배열을 정수형 데이터 배열로 변환하기
arr_str=np.array(['1','1','1','1'])
arr_str.dtype

dtype('<U1')

In [25]:
arr_str1=np.array(['a','b'])
arr_str1
#dtype('<U1')은 문자라는뜻

array(['a', 'b'], dtype='<U1')

In [28]:
arr_int=arr_str.astype(np.float64)
arr_int

array([1., 1., 1., 1.])

### ndarray의 차원과 크기를 변경:reshape()
    1차원->2차원으로 reshape

In [63]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
#2차원 배열로 변경하기, 이때 갯수가 맞아야 한다.
#총10개 이므로 2행 5열이 가능하다.
arr2=arr1.reshape((2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
#값이 초기화 도지 않는 
np.empty((4,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.12199579e-314]])

In [66]:
arr3=arr1.reshape((5,2))
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

2차원 이상 배열을 1차원으로 만들기

In [67]:
#방법1:2차원 이상배열을 1차원 만들기-reshape
arr2.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr4=np.array([[[1,2],[2,4],[4,5]]])
arr4

array([[[1, 2],
        [2, 4],
        [4, 5]]])

In [70]:
arr4.reshape(-1)

array([1, 2, 2, 4, 4, 5])

    reshape(-1,1)  # 1열 형태 (세로 벡터)
    reshape(-1,)  # 1차원 배열

In [72]:
arr1=np.arange(5)
arr1


array([0, 1, 2, 3, 4])

In [78]:
arr2=arr1.reshape(-1,1)
arr2


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [79]:
arr2.ndim

2

In [81]:
arr3=arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4])

In [82]:
arr3.ndim

1

 ### ndarray 데이터 선택
 ### ## (1) 인덱싱 Indexing
### ✔ 1차원

In [83]:
np.int64(8)

np.int64(8)

In [84]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr[0,0]

np.int64(1)

In [87]:
arr[1,1]

np.int64(5)

##(2)슬라이싱(범위값 가져오기)
    1차원ndarray의 슬라이싱

In [89]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr[0:3]

array([1, 2, 3])

In [92]:
arr[:3]

array([1, 2, 3])

In [93]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [94]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<img src="./img/2-1.png" width='700'>

In [97]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [100]:
arr[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [101]:
arr[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [107]:
arr_1=arr[0:2,0]
arr_1.dtype


dtype('int64')

In [108]:
arr_1.ndim

1

In [109]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# (3) 팬시 인덱싱
    리스트나 ndarray로 인덱스로 원하는 값을 가져오는 방벙. 해당 위치의 인덱스에 해당하는 ndarray 값을 반환하는 인덱싱 방법
    1차원 ndarray의 팬시 인덱싱

In [111]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
#리스트
arr[[2,3,7]]

array([3, 4, 8])

In [113]:
idx=np.array([2,4,7])
arr[idx]

array([3, 5, 8])

In [114]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
arr[[0,2],[2,2]]

array([3, 9])

In [119]:
arr[[0,2], 0:2]

array([[1, 2],
       [7, 8]])

In [140]:
arr[[0,1]]

array([1, 2])

# (4) 불린 인덱싱

In [139]:
arr=np.arange(1,10)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
arr[arr>5]

array([6, 7, 8])

In [137]:
arr[(arr>5)&(arr<10)]

array([6, 7, 8])

In [136]:
arr[~(arr>5)]

array([1, 2, 3, 4, 5])

 # ndarray 배열 연산
   dot함수를 사용하여 행렬의 곱 계산하기 , 같은행과 열을 계산

In [142]:
arr8=np.array([[1,2],[3,4]])
arr9=np.array([[5,6],[7,8]])

In [143]:
arr8+arr9

array([[ 6,  8],
       [10, 12]])

In [144]:
np.add(arr8,arr9)

array([[ 6,  8],
       [10, 12]])

In [145]:
arr8*arr9

array([[ 5, 12],
       [21, 32]])

In [146]:
np.multiply(arr8,arr9)

array([[ 5, 12],
       [21, 32]])

In [147]:
arr8-arr9

array([[-4, -4],
       [-4, -4]])

# (2) 행렬 곱 (dot)
  dot함수를 사용하여 배열의 곱 계산하기(배열의 내적)
  -배열의 내적(차원을 맞출때 사용)
  -내적(dot product)은 두 벡터를 곱해서 하나의 숫자(scalar)를 만드는 연산 

<img src='img/2-104.png'>

In [150]:
arr8=np.array([[1,2],
               [3,4]])
arr9=np.array([[5,6],
               [7,8]])

In [153]:
arr8.shape

(2, 2)

In [151]:
arr8*arr9

array([[ 5, 12],
       [21, 32]])

<img src='./img/2-105.png',width='600'>

In [ ]:
arr8.dot(arr9)
#행력 곱을 하려면 반드시 첫번째 배열의 열 개수=두번째 배열의 행 개수 여야 한다.

array([[19, 22],
       [43, 50]])

In [156]:
np.dot(arr8,arr9)

array([[19, 22],
       [43, 50]])

In [160]:
arr5=np.array([[1,2,3,4],
               [3,4,5,6]])
arr6=np.array([[5,6],
               [7,8],
               [9,10],
               [11,12]])

In [163]:
arr5.dot(arr6)

array([[ 90, 100],
       [154, 172]])

In [164]:
arr8=np.array([[2,3,1,5],
               [4,1,6,7]])
arr9=np.array([[1,0,2],
               [3,4,1],
               [0,5,6],
               [7,8,9]])

In [165]:
arr8.dot(arr9)

array([[ 46,  57,  58],
       [ 56,  90, 108]])

In [166]:
arr8.dot(arr9).shape

(2, 3)

# 8️⃣ 선형대수 연산 – 전치행렬
    np.transpose(array):행과 열을 바꾼다 array.T해도 같다.

In [167]:
arr=np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [168]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [169]:
arr.T

array([[1, 3],
       [2, 4]])

In [ ]:
arr=np.array([[1,2],
              [3,4],
              [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [173]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

### 9️⃣ ndarray 배열 결합 – append()
- np.append(a,b, axis=0) 행아래에들어감
- np.append(a,b, axis=1)


In [175]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
b=np.arange(11,14).reshape(1,3)
b

array([[11, 12, 13]])

In [187]:
np.append(a,b,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [ ]:
np.append(a,b.T,axis=1)
#->axis=1:가로방향, 가로로 붙임, 즉 행 기준으로 결합

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [188]:
np.append(a,b.transpose(),axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [190]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [192]:
a.dot(b).shape


()

In [ ]:
# 1) 1부터 10까지 숫자를 가지는 1차원 배열을 생성하시오.
arra=np.arange(1,11)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2)  0으로 채워진 3×4 배열을 생성하시오.
arra=np.zeros((3,4)).astype(int)
arra

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# 3) 1로 채워진 2×5 배열을 생성하시오.
arra=np.ones((2,5))
arra

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [308]:
# 4) 다음 배열의 shape, ndim, dtype을 출력하시오.

# ```python
arr = np.array([[1,2,3],
                [4,5,6]])
# ```

# ---

arr.shape, arr.ndim, arr.dtype

((2, 3), 2, dtype('int64'))

In [212]:
# 5) 다음 배열을 float 타입으로 변환하시오
#arr = np.array([1,2,3,4])
arr=np.array([1,2,3,4]).astype(np.float64)
arr

array([1., 2., 3., 4.])

In [358]:
# ### 문제 6

# 1부터 12까지 숫자를 가지는 배열을 생성하고

# 3×4 형태로 reshape 하시오.

arr=np.arange(1,13).reshape(3,4)
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [361]:
# ### 문제 7

# 위 배열에서

# - 첫 번째 행을 출력하시오.
# - 두 번째 열을 출력하시오.

arr[0]


array([1, 2, 3, 4])

In [328]:
arr[:,1]

array([ 2,  6, 10])

In [329]:
# ### 문제 8

# 위 배열에서 2행 3열 값을 출력하시오.

arr[1,2]

np.int64(7)

In [330]:
arr=np.arange(1,13)
arr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [331]:
# ### 문제 9

# 배열에서 짝수만 출력하시오. (불린 인덱싱 사용)
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [332]:
# ### 문제 10

# 배열의 모든 값에 10을 더하시오. (브로드캐스팅)

arr1=arr+10
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [ ]:
# ### 문제 11

# 다음 두 행렬의 행렬곱(dot)을 구하시오.

# ```python
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

a.dot(b)


array([[19, 22],
       [43, 50]])

In [239]:
# ### 문제 12

# 위 행렬 a의 전치 행렬을 구하시오.
a.T

array([[1, 3],
       [2, 4]])

In [344]:
arrr=np.arange(1,13).reshape(3,4)
arrr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [342]:
# ### 문제 13

# 배열의 각 행의 합을 구하시오. (axis 사용)
arrr.sum(axis=1)

array([10, 26, 42])

In [343]:
# ### 문제 14

# 배열의 각 열의 평균을 구하시오.
arrr.mean(axis=0)

array([5., 6., 7., 8.])

In [ ]:
### 문제 15

# 1~100까지 배열을 만들고

# - 평균
# - 표준편차
# - 최대값
# - 최소값

# 을 구하시오.

arr100=np.arange(1,101)
arr100


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [345]:
np.mean(arr100),np.std(arr100),np.max(arr100),np.min(arr100)

(np.float64(50.5), np.float64(28.86607004772212), np.int64(100), np.int64(1))

In [ ]:
# ### 문제 16

# 랜덤 정수(1~100)를 가지는 5×5 배열을 만들고
arr1001=np.random.randint(1, 101, (5, 5))
arr1001

# 50 이상인 값만 출력하시오.

# np.random.randint(low, high, size)

# | 매개변수 | 의미 |
# | --- | --- |
# | low | 시작값 (포함) |
# | high | 끝값 (❌ 포함 안됨) |
# | size | 배열 크기 |

# ```markdown
# # 0~9 사이 난수 10개
# np.random.randint(0, 10, 10)

# # 3×4 배열 생성
# np.random.randint(0, 100, (3,4))


array([[75, 91, 20, 69, 62],
       [58, 35, 95, 28, 65],
       [26, 70, 20, 72, 86],
       [61, 92, 51,  1, 28],
       [88, 16, 98,  5, 64]], dtype=int32)

In [346]:
arr1001[arr1001>=50]

array([75, 91, 69, 62, 58, 95, 65, 70, 72, 86, 61, 92, 51, 88, 98, 64],
      dtype=int32)

In [263]:
# ### 문제 17

# 다음 배열에서 최댓값의 위치(index)를 구하시오.

np.argmax(arr1001)

np.int64(22)

In [348]:
# ### 문제 18 ( 정답과 함께 제공함)

# 3×3 단위행렬(identity matrix)을 생성하시오.

# ```python
np.eye(3, dtype=int)
np.eye(5, dtype=int)
np.eye(5)
# ```



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [265]:
# ### 문제 19

# 다음 벡터의 내적(dot product)을 구하시오.

# ```python
a = np.array([1,2,3])
b = np.array([4,5,6])



In [266]:
a.dot(b)

np.int64(32)

In [ ]:
# ### 문제 20 (도전 ⭐)

# 다음 조건을 만족하는 배열을 만드시오.

# - 1~16까지 숫자
# - 4×4 배열
# - 각 행의 평균을 구하시오.
# - 평균이 8 이상인 행만 출력하시오.

arr20=np.arange(1,17).reshape(4,4)
arr20



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [352]:
arrMax=arr20.mean(axis=1)
arrMax

array([ 2.5,  6.5, 10.5, 14.5])

In [294]:
m1=arr20[0:1,:]
np.mean(m1)


np.float64(2.5)

In [295]:
m2=arr20[1:2,:]
np.mean(m2)

np.float64(6.5)

In [291]:
m3=arr20[2:3,:]
np.mean(m3)

np.float64(10.5)

In [292]:
m4=arr20[3:4,:]
np.mean(m4)

np.float64(14.5)

In [353]:
arrMax[arrMax>=8]

array([10.5, 14.5])

In [356]:
arr20[[0,2]].mean(axis=1)

array([ 2.5, 10.5])