fish.csv데이터를 로드하여 fish_input과 fish_target으로 나뉘어 담고
훈련과 테스트 세트로 분리한 후 표준화 한다. 
로지스틱 회구로 다중분류 수행한다.
C값을 0.1, 1, 10 으로 바꿔 정확도를 비교하시오
결과


In [89]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#데이터 로드

fish=pd.read_csv('./data/fish.csv')
fish

,Species,Weight,Length,Diagonal,Height,Width
0,Bream,242.0,25.4,30.0,11.5200,4.0200
1,Bream,290.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,26.5,31.1,12.3778,4.6961
3,Bream,363.0,29.0,33.5,12.7300,4.4555
4,Bream,430.0,29.0,34.0,12.4440,5.1340
...,...,...,...,...,...,...
154,Smelt,12.2,12.2,13.4,2.0904,1.3936
155,Smelt,13.4,12.4,13.5,2.4300,1.2690
156,Smelt,12.2,13.0,13.8,2.2770,1.2558
157,Smelt,19.7,14.3,15.2,2.8728,2.0672


In [47]:
pd.unique(fish['Species'])

<StringArray>
['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt']
Length: 7, dtype: str

In [90]:
fish_input=fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target=fish[['Species']].to_numpy()

In [ ]:
#훈련세트만들기
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(fish_input,fish_target)

In [ ]:
#표준화
from sklearn.preprocessing import StandardScaler
ss=StandardScaler() 
ss.fit(train_input) 
train_scaled=ss.transform(train_input) 
test_scaled=ss.transform(test_input)

In [86]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=10, max_iter=1000)
lr.fit(train_scaled,train_target)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",10
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mult

In [87]:
lr.score(train_scaled,train_target)

0.9327731092436975

In [88]:
lr.score(test_scaled,test_target)


0.825

# 문제2 이진 분류

In [ ]:
train_target = train_target.reshape(-1)
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

print(train_bream_smelt)
print(target_bream_smelt)

[[ 0.84406293  0.57515463  0.80488106  1.6757329   0.91398021]
 [ 0.4228291   0.47514966  0.67578393  1.38137412  0.60824455]
 [ 0.0718009   0.07512978  0.27005011  1.11280609  0.14954624]
 [ 0.52111699  0.42514718  0.59279292  1.50196202  0.33284858]
 [ 0.0718009   0.04512829  0.23316522  1.01659869  0.20238788]
 [ 0.49303474  0.27513972  0.4636958   1.45535223  0.61488135]
 [-1.15427039 -1.68495768 -1.72173411 -1.65387962 -2.11000275]
 [ 0.21221218  0.17513475  0.37148357  1.2004086   0.13108959]
 [ 0.21221218  0.14513326  0.37148357  1.16579784  0.22261435]
 [-1.15764026 -1.6249547  -1.69407044 -1.69045038 -2.11834617]
 [-1.16381835 -1.74496066 -1.75861901 -1.70553283 -2.10064801]
 [-0.37751519 -0.2948886  -0.0895776   0.74831749 -0.19063762]
 [-0.23710391 -0.27488761 -0.09879882  0.72388918  0.05618846]
 [ 0.77385729  0.37514469  0.5835717   1.33583993  0.37311189]
 [ 0.73173391  0.47514966  0.64812026  1.58815429  0.48239801]
 [ 0.77385729  0.37514469  0.56512925  1.31729162  0.42

In [68]:
train_bream_smelt[0,]

array([0.84406293, 0.57515463, 0.80488106, 1.6757329 , 0.91398021])

In [69]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(train_bream_smelt,target_bream_smelt)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [70]:
lr.predict(train_bream_smelt[:5])

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream'], dtype=object)

In [71]:
lr.predict_proba(train_bream_smelt[:5])

array([[0.99793423, 0.00206577],
       [0.99548754, 0.00451246],
       [0.98521489, 0.01478511],
       [0.99480218, 0.00519782],
       [0.98389615, 0.01610385]])

In [72]:
lr.classes_

array(['Bream', 'Smelt'], dtype=object)

In [73]:
train_bream_smelt[0,]

array([0.84406293, 0.57515463, 0.80488106, 1.6757329 , 0.91398021])

In [74]:
decisions=lr.decision_function(train_bream_smelt[:5])
decisions 

array([-6.18018227, -5.39639044, -4.19923931, -5.25430409, -4.11246206])

In [75]:
from scipy.special import expit #시그모이드 함수 파이선에서 제공해주는것. 확률값을 알려줌. 
expit(decisions)

array([0.00206577, 0.00451246, 0.01478511, 0.00519782, 0.01610385])

In [76]:
lr.predict_proba(train_bream_smelt[:5])

array([[0.99793423, 0.00206577],
       [0.99548754, 0.00451246],
       [0.98521489, 0.01478511],
       [0.99480218, 0.00519782],
       [0.98389615, 0.01610385]])

In [77]:
lr.coef_,lr.intercept_

(array([[-0.37528434, -0.56992951, -0.64545664, -0.88224157, -0.73819139]]),
 array([-2.8630117]))