# 🎓 머신러닝 종합 실습 문제

## 📊 문제 1 타이타닉 생존 예측
- 다음 데이터를 사용하여 타이타닉 승객의 생존 여부를 예측하는 모델을 만들어보시오.

In [78]:
import seaborn as sns

df = sns.load_dataset("titanic")

## 문제 1 데이터 탐색

다음 항목을 확인하시오.

1️⃣ 데이터의 행과 열의 구조

In [79]:
df.shape

(891, 15)

2️⃣ 각 컬럼의 데이터 타입

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    str     
 8   class        891 non-null    category
 9   who          891 non-null    str     
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str     
 13  alive        891 non-null    str     
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB


3️⃣ 결측치 개수 확인

In [81]:
# df.isna().sum()
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 문제 2 데이터 전처리

다음 변수만 사용하여 모델을 생성하시오.

In [82]:
# pclass
# sex
# age
# fare
# embarked

In [83]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [84]:
df[['pclass','sex','age','fare','embarked', 'survived']]

,pclass,sex,age,fare,embarked,survived
0,3,male,22.0,7.2500,S,0
1,1,female,38.0,71.2833,C,1
2,3,female,26.0,7.9250,S,1
3,1,female,35.0,53.1000,S,1
4,3,male,35.0,8.0500,S,0
...,...,...,...,...,...,...
886,2,male,27.0,13.0000,S,0
887,1,female,19.0,30.0000,S,1
888,3,female,NaN,23.4500,S,0
889,1,male,26.0,30.0000,C,1


In [85]:
import pandas as pd

titanic = df[['pclass','sex','age','fare','embarked', 'survived']].copy()

#결측치 처리
titanic['age']= titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

#독립변수, 종속변수 분리
X = titanic.drop('survived', axis=1)
y = titanic['survived']

#범주형(문자) 변수 변환
X = pd.get_dummies(X, drop_first=True)

X.head()


,pclass,age,fare,sex_male,embarked_Q,embarked_S
0,3,22.0,7.2500,True,False,True
1,1,38.0,71.2833,False,False,False
2,3,26.0,7.9250,False,False,True
3,1,35.0,53.1000,False,False,True
4,3,35.0,8.0500,True,False,True


In [86]:
titanic.tail()

,pclass,sex,age,fare,embarked,survived
886,2,male,27.0,13.00,S,0
887,1,female,19.0,30.00,S,1
888,3,female,28.0,23.45,S,0
889,1,male,26.0,30.00,C,1
890,3,male,32.0,7.75,Q,0


In [87]:
titanic['age'].median()

np.float64(28.0)

In [88]:
titanic['embarked'].mode()[0] 

'S'

## 문제 3 데이터 분할

데이터를 **학습용 데이터와 테스트 데이터**로 분할하시오.

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [90]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

## 문제 4 모델 생성

다음 모델을 사용하여 학습을 수행하시오.

- Logistic Regression(모델 학습 반복 횟수 1000, 랜덤값 고정 42)
- Decision Tree(랜덤값 고정 42)
- Random Forest(랜덤값 고정 42)

In [91]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import  DecisionTreeClassifier
from sklearn.ensemble import  RandomForestClassifier

lr = LogisticRegression(max_iter=1000, random_state=42)
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)

lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

## 문제 5 모델 평가

각 모델의 **정확도(accuracy)**를 출력하고 비교하시오.(반올림)

In [92]:
lr_pred = lr.predict(X_test)
dt_pred = dt.predict(X_test)
rf_pred = rf.predict(X_test)

In [93]:
lr.score(X_test, y_test)

0.7988826815642458

In [94]:
# 예측한 값 비교 
print("모델이 예측한 값 : ", lr_pred[:5])
print("정답 :", y_test.values[:5])

모델이 예측한 값 :  [0 0 0 1 1]
정답 : [1 0 0 1 1]


In [95]:
from sklearn.metrics import accuracy_score
print("Logistic Regression :", round(accuracy_score(y_test, lr_pred), 4))
print("Decision Tree       :", round(accuracy_score(y_test, dt_pred), 4))
print("Random Forest       :", round(accuracy_score(y_test, rf_pred), 4))

Logistic Regression : 0.7989
Decision Tree       : 0.7654
Random Forest       : 0.7989


## 문제 6 혼동 행렬

가장 성능이 좋은 모델을 선택하여

**혼동 행렬(confusion matrix)**을 출력하시오.

In [96]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, rf_pred)
cm

array([[86, 19],
       [17, 57]])

In [97]:
# [[TN FP]
#  [FN TP]]

# - TN(True Negative) : 실제 0, 예측 0  => 86
# - FP(False Positive) : 실제 0, 예측 1  => 19
# - FN(False Negative) : 실제 1, 예측 0  => 17
# - TP(True Positive) 맞게 맞춘 경우 (양성) : 실제 1, 예측 1  => 57

## 문제 7 중요 변수 확인

Random Forest 모델을 사용하여

**가장 중요한 변수(feature)**를 확인하시오.

In [98]:
rf.feature_importances_

array([0.09461079, 0.28142161, 0.31177781, 0.28028642, 0.00879055,
       0.02311283])

In [99]:
importance = pd.Series(rf.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

fare          0.311778
age           0.281422
sex_male      0.280286
pclass        0.094611
embarked_S    0.023113
embarked_Q    0.008791
dtype: float64


In [100]:
lr.coef_

array([[-1.00594150e+00, -2.46096331e-02,  3.61662294e-04,
        -2.45928526e+00, -1.00020785e-01, -5.13978741e-01]])

In [101]:
import pandas as pd

importance = pd.Series(lr.coef_[0], index=X.columns)
importance.sort_values(ascending=False)


fare          0.000362
age          -0.024610
embarked_Q   -0.100021
embarked_S   -0.513979
pclass       -1.005942
sex_male     -2.459285
dtype: float64

In [102]:
# feature_importances_는 트리 기반 모델 전용(얼만나 분할에 기여했는지?)
# Decision Tree, Random Forest

# Logistic Regression
# 계수 크기, coef_, 방향성 있음 (+/-)

In [103]:
# 질문 : CatBoostClassifier 사용하여 분류
import seaborn as sns
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

df = sns.load_dataset("titanic")

titanic = df[['pclass','sex','age','fare','embarked', 'survived']].copy()

#결측치 처리
titanic['age']= titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

#독립변수, 종속변수 분리
X = titanic.drop('survived', axis=1)
y = titanic['survived']

cat_features = ['sex', 'embarked']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = CatBoostClassifier(verbose=0, random_state=42)

model.fit(X_train, y_train, cat_features=cat_features)

print(model.score(X_test, y_test))

0.7988826815642458


In [104]:
model.feature_importances_

array([20.61698097, 40.28633369, 15.49931603, 13.41933004, 10.17803927])

In [105]:
import pandas as pd

importances = pd.Series(model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False)

sex         40.286334
pclass      20.616981
age         15.499316
fare        13.419330
embarked    10.178039
dtype: float64

In [106]:
# RandomForest는 “얼마나 자주 썼는지”
# CatBoost는 “얼마나 도움이 됐는지”를 본다

# 👉 모델이 다르면 중요도 기준도 다르다 → 값이 달라지는 건 정상

# 2. 와인 분류 모델

### 문제 1 데이터 확인

다음 항목을 확인하시오.

- 데이터의 shape
- 클래스 개수
- feature 이름

In [107]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [108]:
wine = load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], shape=(178, 13)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [109]:
type(wine)

#"사이킷런 번치 객체"
# 즉 딕셔너리처럼 여러 데이터를 묶어놓은 객체입니다.

sklearn.utils._bunch.Bunch

In [110]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [111]:
# data -> 입력 데이터 (X)
# target -> 정답 (y)
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [112]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [113]:
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = wine.target

In [114]:
print(X.shape)  #데이터 크기 확인
print(np.unique(y))  #클래스 종류 확인
print(X.columns)  #feature 이름 확인

(178, 13)
[0 1 2]
Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='str')


## 문제 2 데이터 스케일링

데이터를 **StandardScaler**를 사용하여 스케일링 하시오.

In [115]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 문제 3 모델 생성

다음 모델을 사용하여 학습하시오.

- KNN
- SVM (Support Vector Machine) - SVC
- RandomForest

In [116]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# SVM (Support Vector Machine) :  알고리즘 이름
# SVC, SVR, LinearSVC => 클래스이름

# SVC (Support Vector Classifier) - 분류 (Classification)
# SVR - 회귀 (Regression)
# LinearSVC - 선형 SVM (빠른 버전)

In [117]:
knn = KNeighborsClassifier() # random요소가 없음 가까운 k개의 요소를 찾는다.
svm = SVC()
rf = RandomForestClassifier(random_state=42)

In [118]:
knn.fit(X_train_scaled, y_train)
svm.fit(X_train_scaled, y_train)
rf.fit(X_train, y_train)   #스케일링 영향이 적어서 원본 사용 가능

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

## 문제 4 성능 비교

각 모델의 정확도를 비교하시오.

In [119]:
from sklearn.metrics import accuracy_score

knn_pred = knn.predict(X_test_scaled)
svm_pred = svm.predict(X_test_scaled)
rf_pred = rf.predict(X_test)

In [120]:
svm_pred[:5]

array([0, 2, 0, 1, 1])

In [121]:
print("KNN          :", round(accuracy_score(y_test, knn_pred), 4))
print("SVM          :", round(accuracy_score(y_test, svm_pred), 4))
print("RandomForest :", round(accuracy_score(y_test, rf_pred), 4))

KNN          : 0.9722
SVM          : 0.9722
RandomForest : 1.0


# 📊 문제 3 모델 평가 지표

In [122]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

cancer = load_breast_cancer()
cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,

In [123]:
X = pd.DataFrame(cancer.data, columns=cancer.feature_names)
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

- Logistic Regression으로 학습

In [124]:
lr = LogisticRegression(max_iter=10000, random_state=42)
lr.fit(X_train_scaled, y_train)

pred = lr.predict(X_test_scaled)

평가 지표 계산

In [125]:
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

acc = accuracy_score(y_test, pred)
prec = precision_score(y_test, pred)
rec = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
print("accuracy :", round(acc, 4))
print("precision:", round(prec, 4))
print("recall   :", round(rec, 4))
print("f1-score :", round(f1, 4))

accuracy : 0.9825
precision: 0.9861
recall   : 0.9861
f1-score : 0.9861


In [126]:
# accuracy : 전체 중 맞춘 비율
# precision : 양성이라고 예측한 것 중 실제 양성 비율
# recall : 실제 양성 중 찾아낸 비율
# f1-score : precision과 recall의 조화평균

In [127]:
print(classification_report(y_test, pred, digits=4))

              precision    recall  f1-score   support

           0     0.9762    0.9762    0.9762        42
           1     0.9861    0.9861    0.9861        72

    accuracy                         0.9825       114
   macro avg     0.9812    0.9812    0.9812       114
weighted avg     0.9825    0.9825    0.9825       114



In [ ]:
# precision(정밀도)  recall(재현율) f1-score(정밀도와 재현율의 조화 평균) support(실제데이터개수)
# macro avg : 각 클래스 성능 평균, => 계산 방법 (클래스0 + 클래스1) / 2
# weighted avg 데이터 개수 기준 평균 => 계산 방법 클래스별 성능 × 데이터 개수
# (0.9762*42 + 0.9861*72) / 114  = 0.9825

# 📊 문제 4 모델 성능 개선

유방암 데이터셋을 사용하여 모델 성능을 개선하시오.

### 문제 1 RandomForest 모델 생성

RandomForest 모델을 생성하고 학습하시오.

In [129]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [131]:
from sklearn.model_selection import cross_validate
score = cross_validate(rf, X_train,y_train, return_train_score=True)
score

{'fit_time': array([0.19351077, 0.17652845, 0.17453432, 0.17151618, 0.19550323]),
 'score_time': array([0.00994682, 0.00995517, 0.00900364, 0.01296258, 0.01196814]),
 'test_score': array([0.96703297, 0.98901099, 0.92307692, 0.93406593, 0.95604396]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [132]:
# 훈련세트점수
np.mean(score['train_score'])

np.float64(1.0)

In [133]:
#테스트점수(cross_validate test_score)
np.mean(score['test_score'])

np.float64(0.953846153846154)

In [134]:
# 최종 테스트
rf.score(X_test, y_test)

0.956140350877193

### 문제 2 하이퍼파라미터 튜닝

GridSearchCV를 사용하여 다음 파라미터를 튜닝하시오.

In [135]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 3, 5, 10]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    scoring='recall'  # 재현율 기준으로 가장 좋은 모델 선택
)

grid.fit(X_train, y_train)



,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",RandomForestC...ndom_state=42)
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'max_depth': [None, 3, ...], 'n_estimators': [100, 200, ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'recall'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",None
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candidate is displayed;- >2 : the score is also dis

In [ ]:
score = cross_validate(grid, X_train,y_train, return_train_score=True)
score

{'fit_time': array([20.12523055, 20.19002843, 19.31038213, 19.62750673, 19.80605817]),
 'score_time': array([0.01194239, 0.01795411, 0.01296186, 0.01196742, 0.01196814]),
 'test_score': array([0.98245614, 1.        , 0.96491228, 0.94736842, 0.94736842]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [137]:
#테스트점수(cross_validate test_score)
np.mean(score['test_score'])

np.float64(0.968421052631579)

In [138]:
# 훈련데이터
np.mean(score['train_score'])

np.float64(1.0)

In [ ]:
# 최종 테스트
grid.score(X_test, y_test)

0.9722222222222222

## 문제 3 최적 파라미터 출력

다음 항목을 출력하시오.

- best_params_
- best_score_

In [ ]:
grid.best_params_

# None :   트리의 깊이를 제한하지 않는다

{'max_depth': None, 'n_estimators': 100}

In [ ]:
grid.best_score_
# 교차검증(cross validation)에서 나온 validation score의 평균

np.float64(0.968421052631579)

In [144]:
best_model  = grid.best_estimator_

### 문제 4 중요 변수 확인

모델에서 가장 중요한 변수 **상위 5개**를 출력하시오.

In [145]:
best_model.feature_importances_

array([0.06867599, 0.00958431, 0.06957388, 0.04917215, 0.00559816,
       0.01171465, 0.05763806, 0.09088475, 0.00466601, 0.00448887,
       0.01677021, 0.00521386, 0.0096331 , 0.03310446, 0.00349852,
       0.00597922, 0.00431035, 0.00409824, 0.00401198, 0.00444169,
       0.09769574, 0.01859665, 0.07222637, 0.14001599, 0.0124362 ,
       0.01860002, 0.03434013, 0.12952961, 0.00833452, 0.00516632])

In [146]:
importances = pd.Series(best_model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(5)

worst area              0.140016
worst concave points    0.129530
worst radius            0.097696
mean concave points     0.090885
worst perimeter         0.072226
dtype: float64

In [ ]:
# 이 모델에서 유방암 분류에 가장 중요한 변수 TOP5
# worst area  면적이 가장 큰값
# worst concave points 오목한 부분의 개수
# worst radius  종양반지름 가장 큰값
# mean concave points 오목한 부분의 평균값
# worst perimeter 종양 둘레 가장 큰값